### PR TITLE
Initial cleanups

### PR DESCRIPTION
**Pull request by bredelings**
Hi Joe,

This branch has the 5 initial cleanups that we discussed.

-BenRI

### CODE REVIEW

**Comment by shajoezhu** [comment]
Hi @bredelings , would you mind take a look at this please https://travis-ci.org/github/DEploid-dev/DEploid/jobs/763695356#L554

**Comment by bredelings** [comment]
Hi Joe,

This is because the travis build (but not the github-actions build) is 
using an old version of gcc that does not support c++17.  Gcc 5 was 
released in 2015, and the current version is version 10, which was 
released in 2020.

We could fix the travis script, but instead it might be easier to move 
entirely to github actions.  I could probably move the remaining bits 
from travis to github actions.  Then we could decomission travis.  
(Also, I think travis is getting worse -- github actions seems much 
better.  I have switch to github actions in my other projects.).

-BenRI

**Comment by shajoezhu** [comment]
Hi Ben, yes, I agree. Sometimes updating travis yml was a bit painful. I am happy to shift things towards github action. I have a few more things like checking coverage will depend on travis, let me explore how to move those as well. and the for the circleci's i am happy to drop 14.04. though some of the computing labs still have old machines and setup... let me do some checking as well. let me get back to you

**Comment by shajoezhu** [comment]
Many thanks! @bredelings

**Pull request merged**
